/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Pantallas;

import controller.Form;
import java.util.List;
import java.util.function.Function;
import javax.swing.JOptionPane;
import model.Laboratorio;
import model.Usuario;

/**
 *
 * @author derno
 */
public class Listar extends javax.swing.JPanel {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }
    public void mostrarListaUsuarios(List<Usuario> usuarios) {
        if (!usuarios.isEmpty()) {
            String[] columnNames = {"Username", "Nombre Completo", "Rol", "Estado"};
            List<Function<Usuario, Object>> columnFunctions = List.of(
                    Usuario::getUsername,
                    Usuario::getNombreUser,
                    Usuario::getRolUsuario,
                    Usuario::isStatus
            );

            Form<Usuario> form = new Form<>(usuarios, columnNames, columnFunctions);
            jPanel1.removeAll();
            jPanel1.add(form);
            jPanel1.revalidate();
            jPanel1.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "No hay usuarios disponibles", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Método para mostrar una lista de laboratorios
    public void mostrarListaLaboratorios(List<Laboratorio> laboratorios) {
        if (!laboratorios.isEmpty()) {
            String[] columnNames = {"ID", "Nombre", "Facultad", "Escuela", "Departamento", "Administrador"};
            List<Function<Laboratorio, Object>> columnFunctions = List.of(
                    Laboratorio::getId,
                    Laboratorio::getNombreLaboratorio,
                    Laboratorio::getFacultad,
                    Laboratorio::getEscuela,
                    Laboratorio::getDepartamento,
                    lab -> lab.getAdministrador().getUsername() // Assuming getAdministrador() returns a Usuario
            );

            Form<Laboratorio> form = new Form<>(laboratorios, columnNames, columnFunctions);
            jPanel1.removeAll();
            jPanel1.add(form);
            jPanel1.revalidate();
            jPanel1.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "No hay laboratorios disponibles", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
