/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Pantallas;

import controller.Form;
import controller.ListaDeUsuarios;
import controller.ListaLaboratorios;
import java.awt.BorderLayout;
import java.util.List;
import java.util.function.Function;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Laboratorio;
import model.Usuario;
/**
 *
 * @author derno
 */
public class PantallaLaboratorios extends javax.swing.JPanel {
    
    private ListaDeUsuarios listaUsuarios;
    private ListaLaboratorios listaLaboratorios;
    
    public PantallaLaboratorios(ListaDeUsuarios user,ListaLaboratorios labs) {
        this.listaLaboratorios=labs;
        this.listaUsuarios=user;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPantallaLab = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCrearLaboratorio = new javax.swing.JButton();
        BotonModificarUsuario = new javax.swing.JButton();
        BotonEliminarLaboratorio = new javax.swing.JButton();
        BotonListarLab = new javax.swing.JButton();
        BotonListarLabEspecifico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        BackGroundPantallaLab.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(62, 183, 248));

        BotonCrearLaboratorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonCrearLaboratorio.setText("Crear Laboratorio");
        BotonCrearLaboratorio.setAlignmentY(0.0F);
        BotonCrearLaboratorio.setBorder(null);
        BotonCrearLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearLaboratorio.setHideActionText(true);
        BotonCrearLaboratorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCrearLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearLaboratorioActionPerformed(evt);
            }
        });

        BotonModificarUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonModificarUsuario.setText("Modificar Laboratorio");
        BotonModificarUsuario.setToolTipText("");
        BotonModificarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarUsuarioActionPerformed(evt);
            }
        });

        BotonEliminarLaboratorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonEliminarLaboratorio.setText("Eliminar Laboratorio");
        BotonEliminarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEliminarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarLaboratorioActionPerformed(evt);
            }
        });

        BotonListarLab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonListarLab.setText("Listar Laboratorio");
        BotonListarLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonListarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarLabActionPerformed(evt);
            }
        });

        BotonListarLabEspecifico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonListarLabEspecifico.setText("Listar Laboratorio Especifico");
        BotonListarLabEspecifico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonListarLabEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarLabEspecificoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarLabEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonListarLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEliminarLaboratorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCrearLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotonCrearLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonEliminarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonListarLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonListarLabEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono Laboratorios.png"))); // NOI18N

        javax.swing.GroupLayout BackGroundPantallaLabLayout = new javax.swing.GroupLayout(BackGroundPantallaLab);
        BackGroundPantallaLab.setLayout(BackGroundPantallaLabLayout);
        BackGroundPantallaLabLayout.setHorizontalGroup(
            BackGroundPantallaLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPantallaLabLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(144, 144, 144)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(186, 186, 186))
        );
        BackGroundPantallaLabLayout.setVerticalGroup(
            BackGroundPantallaLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPantallaLabLayout.createSequentialGroup()
                .addGroup(BackGroundPantallaLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundPantallaLabLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackGroundPantallaLabLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)))
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPantallaLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPantallaLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearLaboratorioActionPerformed
        String nombreLaboratorio = JOptionPane.showInputDialog("Ingrese el nombre del laboratorio:");
        String facultad = JOptionPane.showInputDialog("Ingrese la facultad:");
        String escuela = JOptionPane.showInputDialog("Ingrese la escuela:");
        String departamento = JOptionPane.showInputDialog("Ingrese el departamento:");
        String adminUsername = JOptionPane.showInputDialog("Ingrese el nombre de usuario del administrador:");
        String id = listaUsuarios.listarUsuarioPorNombre(adminUsername); // Busca el usuario con el nombre de usuario
        Usuario administrador=listaUsuarios.listarUsuario(id);
        if (administrador != null) {
            boolean exito = listaLaboratorios.crearLaboratorio(administrador, nombreLaboratorio, facultad, escuela, departamento, administrador);
            if (exito) {
                JOptionPane.showMessageDialog(null, "Laboratorio creado exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al crear el laboratorio");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Administrador no encontrado");
        }
    }//GEN-LAST:event_BotonCrearLaboratorioActionPerformed

    private void BotonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarUsuarioActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del laboratorio a modificar:");
        String id=listaLaboratorios.listarLaboratorioPorNombre(nombre);
        Laboratorio laboratorioExistente = listaLaboratorios.listarLaboratorio(id);
        if (laboratorioExistente != null) {
            String nuevoNombreLaboratorio = JOptionPane.showInputDialog("Ingrese el nuevo nombre del laboratorio:", laboratorioExistente.getNombreLaboratorio());
            String nuevaFacultad = JOptionPane.showInputDialog("Ingrese la nueva facultad:", laboratorioExistente.getFacultad());
            String nuevaEscuela = JOptionPane.showInputDialog("Ingrese la nueva escuela:", laboratorioExistente.getEscuela());
            String nuevoDepartamento = JOptionPane.showInputDialog("Ingrese el nuevo departamento:", laboratorioExistente.getDepartamento());
            String adminUsername = JOptionPane.showInputDialog("Ingrese el nombre de usuario del administrador:");
            String ID = listaUsuarios.listarUsuarioPorNombre(adminUsername); // Busca el usuario con el nombre de usuario
            Usuario nuevoAdministrador=listaUsuarios.listarUsuario(ID);
            if (nuevoAdministrador != null) {
                boolean exito = listaLaboratorios.modificarLaboratorio(nuevoAdministrador, id, nuevoNombreLaboratorio, nuevaFacultad, nuevaEscuela, nuevoDepartamento, nuevoAdministrador);
                if (exito) {
                    JOptionPane.showMessageDialog(null, "Laboratorio modificado exitosamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al modificar el laboratorio");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Administrador no encontrado");
            }
        }
    }//GEN-LAST:event_BotonModificarUsuarioActionPerformed

    private void BotonEliminarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarLaboratorioActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del laboratorio a modificar:");
        String id=listaLaboratorios.listarLaboratorioPorNombre(nombre);
        Laboratorio laboratorioExistente = listaLaboratorios.listarLaboratorio(id);

        if (laboratorioExistente != null) {
            listaLaboratorios.eliminarLaboratorio(laboratorioExistente.getAdministrador(), id);
            JOptionPane.showMessageDialog(null, "Laboratorio eliminado exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar el laboratorio");
        }
    }//GEN-LAST:event_BotonEliminarLaboratorioActionPerformed

    private void BotonListarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarLabActionPerformed
        List<Laboratorio> laboratorios = listaLaboratorios.listarLaboratorios();
        if(!laboratorios.isEmpty()){
            Listar pl = new Listar();
        pl.setSize(1100, 610);
        pl.setLocation(0, 0);
        pl.mostrarListaLaboratorios(laboratorios);
        BackGroundPantallaLab.removeAll();
        BackGroundPantallaLab.add(pl, BorderLayout.CENTER);
        } else{
            JOptionPane.showMessageDialog(null, "No hay laboratorios disponibles");
        }
        BackGroundPantallaLab.revalidate();
        BackGroundPantallaLab.repaint();
    }//GEN-LAST:event_BotonListarLabActionPerformed

    private void BotonListarLabEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarLabEspecificoActionPerformed
    String nombre = JOptionPane.showInputDialog("Ingrese el nombre del laboratorio a mostrar:");
    String id=listaLaboratorios.listarLaboratorioPorNombre(nombre);
    Laboratorio laboratorioExistente = listaLaboratorios.listarLaboratorio(id);
    if (laboratorioExistente != null) {
        String[] columnNames = {"Campo", "Valor"};
        List<String[]> data = List.of(
            new String[]{"Nombre", laboratorioExistente.getNombreLaboratorio()},
            new String[]{"Facultad", laboratorioExistente.getFacultad()},
            new String[]{"Escuela", laboratorioExistente.getEscuela()},
            new String[]{"Departamento", laboratorioExistente.getDepartamento()},
            new String[]{"Administrador", laboratorioExistente.getAdministrador().getUsername()}
        );
        List<Function<String[], Object>> columnFunctions = List.of(
            row -> row[0],
            row -> row[1]
        );
        Form<String[]> form = new Form<>(data, columnNames, columnFunctions);
        JFrame frame = new JFrame("Información del Laboratorio");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(form);
        frame.pack();
        frame.setVisible(true);
    }
    }//GEN-LAST:event_BotonListarLabEspecificoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPantallaLab;
    private javax.swing.JButton BotonCrearLaboratorio;
    private javax.swing.JButton BotonEliminarLaboratorio;
    private javax.swing.JButton BotonListarLab;
    private javax.swing.JButton BotonListarLabEspecifico;
    private javax.swing.JButton BotonModificarUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
