/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Pantallas;

import controller.ListaDeUsuarios;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Usuario;
/**
 *
 * @author derno
 */
public class PantallaUsuarios extends javax.swing.JPanel {

    private ListaDeUsuarios ListaUsuarios; 
    private JPanel contenidoMain;
    
    public PantallaUsuarios(JPanel contenidoMain) { // Modificar el constructor
        initComponents();
        this.contenidoMain = contenidoMain; // Asignar el valor del parámetro al campo
        ListaUsuarios = new ListaDeUsuarios();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCrearUsuario = new javax.swing.JButton();
        BotonModificarUsuario = new javax.swing.JButton();
        BotonEliminarUsuario = new javax.swing.JButton();
        BotonListarUsuario = new javax.swing.JButton();
        BotonListarUsuarioEspecifico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(62, 183, 248));

        BotonCrearUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonCrearUsuario.setText("Crear Usuario");
        BotonCrearUsuario.setAlignmentY(0.0F);
        BotonCrearUsuario.setBorder(null);
        BotonCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearUsuario.setHideActionText(true);
        BotonCrearUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearUsuarioActionPerformed(evt);
            }
        });

        BotonModificarUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonModificarUsuario.setText("Modificar Usuario");
        BotonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarUsuarioActionPerformed(evt);
            }
        });

        BotonEliminarUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonEliminarUsuario.setText("Eliminar Usuario");
        BotonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarUsuarioActionPerformed(evt);
            }
        });

        BotonListarUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonListarUsuario.setText("Listar Usuario");
        BotonListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarUsuarioActionPerformed(evt);
            }
        });

        BotonListarUsuarioEspecifico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonListarUsuarioEspecifico.setText("Listar Usuario Especifico");
        BotonListarUsuarioEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarUsuarioEspecificoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarUsuarioEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(BotonListarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEliminarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotonCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonEliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonListarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(BotonListarUsuarioEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono Imagen Usuarios(2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(144, 144, 144)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)))
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearUsuarioActionPerformed
      String username = JOptionPane.showInputDialog("Ingrese el nombre de usuario:");
      String contrasena = JOptionPane.showInputDialog("Ingrese la contraseña:");
      String nombreCompleto = JOptionPane.showInputDialog("Ingrese el nombre completo:");
      String privilegiosStr = JOptionPane.showInputDialog("Ingrese los privilegios (separados por comas):");
      ArrayList<String> privilegios = new ArrayList<>(Arrays.asList(privilegiosStr.split(",")));
      String rol = JOptionPane.showInputDialog("Ingrese el rol:");
      String statusStr = JOptionPane.showInputDialog("Ingrese el estado (true/false):");

      Usuario nuevoUsuario = new Usuario(username, contrasena, nombreCompleto, privilegios, rol, Boolean.parseBoolean(statusStr));

      boolean exito = ListaUsuarios.crearUsuario(nuevoUsuario, username, contrasena, nombreCompleto, privilegios, rol, statusStr);
      if (exito) {
          JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
      } else {
          JOptionPane.showMessageDialog(null, "Error al crear el usuario");
      }
    }//GEN-LAST:event_BotonCrearUsuarioActionPerformed

    private void BotonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarUsuarioActionPerformed
        String id = JOptionPane.showInputDialog("Ingrese el ID del usuario a modificar:");
        Usuario usuarioExistente = ListaUsuarios.listarUsuario(id);

        if (usuarioExistente != null) {
            String nuevoUsername = JOptionPane.showInputDialog("Ingrese el nuevo nombre de usuario:", usuarioExistente.getUsername());
            String nuevaContrasena = JOptionPane.showInputDialog("Ingrese la nueva contraseña:", usuarioExistente.getContrasena());
            String nuevoNombreCompleto = JOptionPane.showInputDialog("Ingrese el nuevo nombre completo:", usuarioExistente.getNombreUser());
            String privilegiosStr = JOptionPane.showInputDialog("Ingrese los nuevos privilegios (separados por comas):", String.join(",", usuarioExistente.getPrivilegios()));
            ArrayList<String> nuevosPrivilegios = new ArrayList<>(Arrays.asList(privilegiosStr.split(",")));
            String nuevoRol = JOptionPane.showInputDialog("Ingrese el nuevo rol:", usuarioExistente.getRolUsuario());
            String statusStr = JOptionPane.showInputDialog("Ingrese el nuevo estado (true/false):", Boolean.toString(usuarioExistente.isStatus()));

            boolean exito = ListaUsuarios.modificarUsuarios(usuarioExistente, id, nuevoUsername, nuevaContrasena, nuevoNombreCompleto, nuevosPrivilegios, nuevoRol, statusStr);
            if (exito) {
                JOptionPane.showMessageDialog(null, "Usuario modificado exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar el usuario");
            }
        }
    }//GEN-LAST:event_BotonModificarUsuarioActionPerformed

    private void BotonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarUsuarioActionPerformed
        String id = JOptionPane.showInputDialog("Ingrese el ID del usuario a eliminar:");
        Usuario usuarioExistente = ListaUsuarios.listarUsuario(id);

        if (usuarioExistente != null) {
            boolean exito = ListaUsuarios.eliminarUsuarios(usuarioExistente, id);
            if (exito) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar el usuario");
            }
        }
    }//GEN-LAST:event_BotonEliminarUsuarioActionPerformed

    private void BotonListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarUsuarioActionPerformed

            Listar pl = new Listar();
            pl.setSize(1100,610);
            pl.setLocation(0,0);
            contenidoMain.removeAll();
            contenidoMain.add(pl, BorderLayout.CENTER);
            contenidoMain.revalidate();
            contenidoMain.repaint();
    }//GEN-LAST:event_BotonListarUsuarioActionPerformed

    private void BotonListarUsuarioEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarUsuarioEspecificoActionPerformed
        String id = JOptionPane.showInputDialog("Ingrese el ID del usuario a mostrar:");
        Usuario usuario = ListaUsuarios.listarUsuario(id);

        if (usuario != null) {
            StringBuilder info = new StringBuilder();
            info.append("ID: ").append(usuario.getId()).append("\n");
            info.append("Username: ").append(usuario.getUsername()).append("\n");
            info.append("Nombre Completo: ").append(usuario.getNombreUser()).append("\n");
            info.append("Privilegios: ").append(String.join(", ", usuario.getPrivilegios())).append("\n");
            info.append("Rol: ").append(usuario.getRolUsuario()).append("\n");
            info.append("Estado: ").append(usuario.isStatus()).append("\n");

            JOptionPane.showMessageDialog(null, info.toString(), "Información del Usuario", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonListarUsuarioEspecificoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearUsuario;
    private javax.swing.JButton BotonEliminarUsuario;
    private javax.swing.JButton BotonListarUsuario;
    private javax.swing.JButton BotonListarUsuarioEspecifico;
    private javax.swing.JButton BotonModificarUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
